apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app2.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.app2.name }}
  ports:
  - port: {{ .Values.app2.port }}
    targetPort: {{ .Values.app2.targetPort }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app2.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.app2.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app2.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app2.name }}
    spec:
      containers:
      - name: {{ .Values.app2.name }}
        image: "{{ .Values.app2.image }}:{{ .Values.app2.tag }}"
        ports:
        - containerPort: {{ .Values.app2.targetPort }}
        env:
        - name: PORT
          value: {{ .Values.app2.port }}
        - name: APP_NAME
          value: {{ .Values.app2.name }}
