apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jehielmartinez/k8s-test
    targetRevision: main
    path: helm/app
    helm:
      valueFiles:
      - values.yaml
      - values-dev.yaml
      ignoreMissingValueFiles: true
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
    automated:
      selfHeal: true
      prune: true